- !!python/object/new:geometry_msgs.msg._PointStamped.PointStamped
  state:
  - !!python/object/new:std_msgs.msg._Header.Header
    state:
    - 0
    - !!python/object/new:rospy.rostime.Time
      state: [1677161758, 14553070]
    - xtion_rgb_optical_frame
  - !!python/object/new:geometry_msgs.msg._Point.Point
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        AAAAgL4f0D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAoASh078=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAwMh26j8=
- !!python/object/new:geometry_msgs.msg._PointStamped.PointStamped
  state:
  - !!python/object/new:std_msgs.msg._Header.Header
    state:
    - 0
    - !!python/object/new:rospy.rostime.Time
      state: [1677161758, 14561891]
    - xtion_rgb_optical_frame
  - !!python/object/new:geometry_msgs.msg._Point.Point
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAoHse078=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAYJdr078=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAQAwC6z8=
- !!python/object/new:geometry_msgs.msg._PointStamped.PointStamped
  state:
  - !!python/object/new:std_msgs.msg._Header.Header
    state:
    - 0
    - !!python/object/new:rospy.rostime.Time
      state: [1677161758, 14569997]
    - xtion_rgb_optical_frame
  - !!python/object/new:geometry_msgs.msg._Point.Point
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA+H8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA+H8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAAAAA+H8=
- !!python/object/new:geometry_msgs.msg._PointStamped.PointStamped
  state:
  - !!python/object/new:std_msgs.msg._Header.Header
    state:
    - 0
    - !!python/object/new:rospy.rostime.Time
      state: [1677161758, 14578104]
    - xtion_rgb_optical_frame
  - !!python/object/new:geometry_msgs.msg._Point.Point
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAYHHZzz8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAoI1Cwj8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AAAAQIlB4D8=
