play_motion:
  motions:
    close_gripper_pawn:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.004, 0.004]
        time_from_start: 1.0

    close_gripper_rook:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.008, 0.008]
        time_from_start: 1.0

    close_gripper_knight:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.0035, 0.0035] # 0035
        time_from_start: 1.0

    close_gripper_bishop:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.007, 0.007]
        time_from_start: 1.0

    close_gripper_queen:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.008, 0.008]
        time_from_start: 1.0

    close_gripper_king:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.009, 0.009]
        time_from_start: 1.0

    open_gripper:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0.025, 0.025]
        time_from_start: 1.0

    close_gripper:
      joints: [gripper_left_finger_joint, gripper_right_finger_joint]
      points:
      - positions: [0, 0]
        time_from_start: 1.0